---
apiVersion: v2
appVersion: "1.0"
description: A Helm chart for deploying the metal control plane in K8s
name: metal-control-plane
version: 0.3.18
dependencies:
  - name: meilisearch
    version: ~0.1.44
    repository: https://meilisearch.github.io/meilisearch-kubernetes
    condition: auditing.enabled
