---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "postgreslet.fullname" . }}-webhook-tls
  namespace: {{ .Release.Namespace }}
spec:
  dnsNames:
    - webhook.pgaas-dev.fits.cloud
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt-prod
  secretName: {{ include "postgreslet.fullname" . }}-webhook-tls
  usages:
    - digital signature
    - key encipherment