{{- if .Values.postgreslet.enableFsGroupChangePolicyWebhook }}
{{- if .Values.postgreslet.tlsClusterIssuer }}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "postgreslet.fullname" . }}-webhook-tls
  namespace: {{ .Release.Namespace }}
spec:
  dnsNames: 
  - {{ include "postgreslet.fullname" . }}-webhook.{{ .Release.Namespace }}.svc
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: {{ .Values.postgreslet.tlsClusterIssuer | quote  }}
  secretName: {{ include "postgreslet.fullname" . }}-webhook-tls
{{- end }}
{{- end }}