apiVersion: v1
data:
  postgres-exporter-service-port: {{ .Values.sidecars.exporter.servicePort | quote }}
  postgres-exporter-service-target-port: {{ .Values.sidecars.exporter.containerPort | quote }}
{{- if .Values.sidecars.exporter.enableStatementsQuery }}
  queries.yaml: {{ printf "%s\n%s" .Values.sidecars.exporter.queries .Values.sidecars.exporter.queriesStatements | b64enc  }}
{{- else }}
  queries.yaml: {{ b64enc .Values.sidecars.exporter.queries }}
{{- end }}
  fluent-bit.conf: {{ b64enc .Values.sidecars.fluentbit.conf }}
  sidecars: |
    - name: postgres-exporter
{{- if .Values.sidecars.exporter.image }}
      image: {{ .Values.sidecars.exporter.image }}
{{- else }}
      image: "{{ .Values.sidecars.exporter.imageRepository }}:{{ .Values.sidecars.exporter.imageTag }}"
{{- end }}
      ports:
        - name: exporter
          containerPort: {{ .Values.sidecars.exporter.containerPort }}
          protocol: TCP
      resources:
        requests:
          cpu: {{ .Values.sidecars.exporter.resources.requests.cpu }}
          memory: {{ .Values.sidecars.exporter.resources.requests.memory }}
        limits:
          cpu: {{ .Values.sidecars.exporter.resources.limits.cpu }}
          memory: {{ .Values.sidecars.exporter.resources.limits.memory }}
      env:
        - name: DATA_SOURCE_URI
          value: 127.0.0.1:5432/postgres?sslmode=disable
        - name: DATA_SOURCE_USER
          value: monitoring
        - name: DATA_SOURCE_PASS
          valueFrom:
            secretKeyRef:
              key: password
        - name: PG_EXPORTER_EXTEND_QUERY_PATH
          value: /metrics/queries.yaml
        - name: PG_EXPORTER_CONSTANT_LABELS
          value: "postgres_partition={{ .Values.postgreslet.partitionId }},server=$(POD_NAME)"
    - name: postgres-fluentbit
{{- if .Values.sidecars.fluentbit.image }}
      image: {{ .Values.sidecars.fluentbit.image }}
{{- else }}
      image: "{{ .Values.sidecars.fluentbit.imageRepository }}:{{ .Values.sidecars.fluentbit.imageTag }}"
{{- end }}
      resources:
        requests:
          cpu: {{ .Values.sidecars.fluentbit.resources.requests.cpu }}
          memory: {{ .Values.sidecars.fluentbit.resources.requests.memory }}
        limits:
          cpu: {{ .Values.sidecars.fluentbit.resources.limits.cpu }}
          memory: {{ .Values.sidecars.fluentbit.resources.limits.memory }}
  additional-volumes: |
    - name: empty
      mountPath: /opt/empty
      targetContainers:
        - all
      volumeSource:
        emptyDir: {}
    - name: postgres-exporter-configmap
      mountPath: /metrics
      targetContainers:
        - postgres-exporter
      volumeSource:
        configMap:
          name: postgres-sidecars-configmap
          items:
            - key: queries.yaml
              path: queries.yaml
    - name: postgres-fluentbit-configmap
      mountPath: /fluent-bit/etc
      targetContainers:
        - postgres-fluentbit
      volumeSource:
        configMap:
          name: postgres-sidecars-configmap
          items:
            - key: fluent-bit.conf
              path: fluent-bit.conf
kind: ConfigMap
metadata:
  name: {{ include "postgreslet.fullname" . }}-postgres-sidecars
  namespace: {{ .Release.Namespace }}
{{- with .Values.podAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
{{- end }}
  labels:
    {{- include "postgreslet.labels" . | nindent 4 }}
