---
apiVersion: v1
kind: Service
metadata:
{{- with .Values.podAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
{{- end }}
  name: {{ include "postgreslet.fullname" . }}-metrics
  namespace: {{ .Release.Namespace }}
  labels:
    control-plane: controller-manager
    {{- include "postgreslet.labels" . | nindent 4 }}
spec:
  ports:
    - name: metrics
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    control-plane: controller-manager
    {{- include "postgreslet.selectorLabels" . | nindent 4 }}
  type: ClusterIP
---
{{- if .Values.postgreslet.enableFsGroupChangePolicyWebhook }}
{{- if .Values.postgreslet.tlsClusterIssuer }}
apiVersion: v1
kind: Service
metadata:
{{- with .Values.podAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
{{- end }}
  name: {{ include "postgreslet.fullname" . }}-webhook
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - port: 443
      targetPort: 9443
  selector:
    control-plane: controller-manager
    {{- include "postgreslet.selectorLabels" . | nindent 4 }}
{{- end }}
{{- end }}
