---
set_resource_limits: true

zap_encoding: json
zap_level: debug

images:
  metal_console:
    image: ghcr.io/metal-stack/metal-console
    imagePullPolicy: IfNotPresent
    tag: latest
  metal_console_token_refresher:
    image: ghcr.io/metal-stack/metal-token-refresher
    imagePullPolicy: IfNotPresent
    tag: latest

resources:
  metal_console:
    requests:
      memory: "64Mi"
      cpu: "40m"
    limits:
      memory: "128Mi"
      cpu: "60m"
  metal_console_token_refresher:
    requests:
      memory: "32Mi"
      cpu: "20m"
    limits:
      memory: "64Mi"
      cpu: "40m"

pod_disruption_budget:
  metal_console:
    enabled: false
    min_available: 1

ports:
  metal_apiserver: 8080
  metal_console: 10001

metal_apiserver:
  base_path: ""

metal_console:
  enabled: false
  replicas: 3
  tcpRoute:
    enabled: false
    annotations: {}
    parentRefs: []
    #   - name: metal-gateway
    #     namespace: gateway-system
    #     sectionName: metal-console
  bmc_proxy:
    tls:
      server_key_enc: ""
      server_pub_enc: ""
      client_key_enc: ""
      client_cert_enc: ""
      ca_cert_enc: ""
  token_secret_ref:
    name: metal-console-token
    key: token

metal_console_token_refresher:
  enabled: false
  schedule: "@hourly"

metal_registry_auth_enabled:
