on:
  pull_request:
    paths:
      - charts/csi-driver-lvm/**
    branches:
      - master

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Create k8s Kind Cluster
      uses: helm/kind-action@v1.10.0
      with:
        version: v0.24.0
        install_only: true

    - name: Test
      run: |
        make test-csi-driver-lvm
        make cleanup-csi-driver-lvm
