on:
  pull_request:
    paths:
      - charts/csi-driver-lvm/**
    branches:
      - master

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Create k8s Kind Cluster
      uses: helm/kind-action@v1.3.0
      with:
        install_only: true

    - name: Test
      run: |
        for i in 100 101; do fallocate -l 1G loop${i}.img ; sudo losetup /dev/loop${i} loop${i}.img; done
        sudo losetup -a
        make test-csi-driver-lvm
