on:
  workflow_run:
    workflows: ["Pull Request"]
    types:
      - completed
  pull_request:
    paths:
      - charts/csi-driver-lvm/**
    branches:
      - master

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  PROVISIONER_IMAGE_NAME: ${{ github.repository }}-provisioner

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        repository: https://github.com/metal-stack/csi-driver-lvm

    - name: Create k8s Kind Cluster
      uses: helm/kind-action@v1.3.0
      with:
        install_only: true

    - name: Test
      run: |
        for i in 100 101; do fallocate -l 1G loop${i}.img ; sudo losetup /dev/loop${i} loop${i}.img; done
        sudo losetup -a
        HELM_REPO=https://helm.metal-stack.io/pull_requests/${GITHUB_HEAD_REF##*/} make test
