---
apiVersion: v1
kind: ConfigMap
metadata:
  name: default-tenant
data:
  tenant.yaml: |
    {{ .Values.masterdata_api.tenants | nindent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: default-project
data:
  project.yaml: |
    {{ .Values.masterdata_api.projects | nindent 4 }}
---
apiVersion: v1
kind: Secret
metadata:
  name: masterdata-api-tls
type: Opaque
data:
  ca.pem: {{ .Values.masterdata_api.ca }}
  client.pem: {{ .Values.masterdata_api.client_cert }}
  client-key.pem: {{ .Values.masterdata_api.client_key }}
  server-key.pem: {{ .Values.masterdata_api.cert_key }}
  server.pem: {{ .Values.masterdata_api.cert }}
