---
apiVersion: v1
kind: Secret
metadata:
  labels:
    app: metal-api
  name: metal-api
type: Opaque
stringData:
  view_key: {{ .Values.metal_api.view_key }}
  edit_key: {{ .Values.metal_api.edit_key }}
  admin_key: {{ .Values.metal_api.admin_key }}
---
apiVersion: v1
kind: Secret
metadata:
  labels:
    app: metal-api-grpc
  name: metal-api-grpc
data:
  server_key.pem: {{ .Values.metal_api.grpc.tls.server_key_enc }}
  server.pem: {{ .Values.metal_api.grpc.tls.server_cert_enc }}
  ca.pem: {{ .Values.metal_api.grpc.tls.ca_cert_enc }}
{{- if .Values.metal_api.bmc.superuser.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  labels:
    app: metal-api-bmc
  name: metal-api-bmc
data:
  superuser.pwd: {{ .Values.metal_api.bmc.superuser.pwd_enc }}
{{- end }}
{{- if .Values.metal_api.s3.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  labels:
    app: metal-api-s3
  name: metal-api-s3
type: Opaque
stringData:
  s3_address: {{ .Values.metal_api.s3.address }}
  s3_key: {{ .Values.metal_api.s3.key }}
  s3_secret: {{ .Values.metal_api.s3.secret }}
  s3_firmware_bucket: {{ .Values.metal_api.s3.firmware_bucket }}
{{- end }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: metal-api
  name: metal-api
spec:
  replicas: {{ .Values.metal_api.replicas }}
  selector:
    matchLabels:
      app: metal-api
  template:
    metadata:
      labels:
        app: metal-api
    spec:
      restartPolicy: Always
      # it's better to disable the service links as the default args do not work properly otherwise (metal#64)
      enableServiceLinks: False
      containers:
      - name: metal-api
        image: {{ .Values.images.metal_api.image }}:{{ .Values.images.metal_api.tag }}
        imagePullPolicy: {{ .Values.images.metal_api.imagePullPolicy }}
        ports:
        - containerPort: 8080
        - containerPort: 50051
          protocol: TCP
        - containerPort: 2112
        readinessProbe:
          httpGet:
            path: {{ .Values.metal_api.base_path }}v1/health
            port: 8080
          initialDelaySeconds: 15
          successThreshold: 1
          timeoutSeconds: 10
        env:
        - name: METAL_API_BIND_ADDR
          value: 0.0.0.0
        - name: METAL_API_BASE_PATH
          value: {{ .Values.metal_api.base_path }}
        - name: METAL_API_LOG_LEVEL
          value: {{ .Values.metal_api.log_level }}
        - name: METAL_API_INIT_DATA_STORE
          value: "false"
        - name: METAL_API_DB_ADDR
          value: {{ .Values.metal_api.db_address }}
        - name: METAL_API_DB_PASSWORD
          value: {{ .Values.metal_api.db_password }}
        - name: METAL_API_DEX_ADDR
          value: {{ .Values.metal_api.dex_address }}
        - name: METAL_API_DEX_CLIENTID
          value: {{ .Values.metal_api.dex_clientid }}
        - name: METAL_API_HMAC_VIEW_KEY
          valueFrom:
            secretKeyRef:
              name: metal-api
              key: view_key
        - name: METAL_API_HMAC_EDIT_KEY
          valueFrom:
            secretKeyRef:
              name: metal-api
              key: edit_key
        - name: METAL_API_HMAC_ADMIN_KEY
          valueFrom:
            secretKeyRef:
              name: metal-api
              key: admin_key
        - name: METAL_API_IPAM_GRPC_SERVER_ENDPOINT
          value: {{ .Values.metal_api.ipam_grpc_server_endpoint }}
        - name: METAL_API_PROVIDER_TENANT
          value: "{{ .Values.masterdata_api.provider_tenant }}"
        - name: METAL_API_NSQLOOKUPD_ADDR
          value: {{ .Values.metal_api.nsq.lookupd_address }}
        - name: METAL_API_NSQD_TCP_ADDR
          value: {{ .Values.metal_api.nsq.tcp_address }}
        - name: METAL_API_NSQD_HTTP_ENDPOINT
          value: {{ .Values.metal_api.nsq.http_address }}
{{- if .Values.metal_api.nsq.tls.enabled }}
        - name: METAL_API_NSQD_CA_CERT_FILE
          value: /certs/nsq/ca.pem
        - name: METAL_API_NSQD_CLIENT_CERT_FILE
          value: /certs/nsq/client.pem
{{- end }}
        - name: METAL_API_GRPC_TLS_ENABLED
          value: "{{ .Values.metal_api.grpc.tls.enabled }}"
{{- if .Values.metal_api.grpc.tls.enabled }}
        - name: METAL_API_GRPC_CA_CERT_FILE
          value: /certs/grpc/ca.pem
        - name: METAL_API_GRPC_SERVER_CERT_FILE
          value: /certs/grpc/server.pem
        - name: METAL_API_GRPC_SERVER_KEY_FILE
          value: /certs/grpc/server_key.pem
{{- end }}
{{- if .Values.metal_api.bmc.superuser.enabled }}
        - name: METAL_API_BMC_SUPERUSER_PWD_FILE
          value: /bmc/superuser.pwd
{{- end }}
{{- if .Values.metal_api.s3.enabled }}
        - name: METAL_API_S3_ADDRESS
          valueFrom:
            secretKeyRef:
              name: metal-api-s3
              key: s3_address
        - name: METAL_API_S3_KEY
          valueFrom:
            secretKeyRef:
              name: metal-api-s3
              key: s3_key
        - name: METAL_API_S3_SECRET
          valueFrom:
            secretKeyRef:
              name: metal-api-s3
              key: s3_secret
        - name: METAL_API_S3_FIRMWARE_BUCKET
          valueFrom:
            secretKeyRef:
              name: metal-api-s3
              key: s3_firmware_bucket
{{- end }}
{{- if .Values.metal_api.headscale.enabled }}
        - name: METAL_API_HEADSCALE_API_KEY
          value: "{{ .Values.metal_api.headscale.api_key }}"
        - name: METAL_API_HEADSCALE_ADDR
          value: {{ .Values.metal_api.headscale.internal_api_address }}
        - name: METAL_API_HEADSCALE_CP_ADDR
          value: {{ .Values.metal_api.headscale.control_plane_address }}
{{- end }}
        - name: METAL_API_MASTERDATA_HMAC
          value: "{{ .Values.masterdata_api.hmac }}"
        - name: METAL_API_MASTERDATA_HOSTNAME
          value: masterdata-api
        - name: METAL_API_MASTERDATA_PORT
          value: "{{ .Values.ports.masterdata_api }}"
        - name: METAL_API_MASTERDATA_CAPATH
          value: /certs/masterdata-api/ca.pem
        - name: METAL_API_MASTERDATA_CERTPATH
          value: /certs/masterdata-api/client.pem
        - name: METAL_API_MASTERDATA_CERTKEYPATH
          value: /certs/masterdata-api/client-key.pem
        - name: METAL_API_PASSWORD_REASON_MINLENGTH
          value: "{{ .Values.metal_api.password_reason_minlength }}"
{{- if .Values.metal_api.release_version }}
        - name: METAL_API_RELEASE_VERSION
          value: "{{ .Values.metal_api.release_version }}"
{{- end }}
        - name: METAL_API_MINIMUM_CLIENT_VERSION
          value: "{{ .Values.metal_api.minimum_client_version }}"
{{- if .Values.auditing.enabled }}
        - name: METAL_API_AUDITING_ENABLED
          value: "true"
        - name: METAL_API_AUDITING_URL
          value: "{{ .Values.auditing.url }}"
        - name: METAL_API_AUDITING_API_KEY
          valueFrom:
            secretKeyRef:
              name: "{{ .Values.auditing.existingMasterKeySecret }}"
              key: MEILI_MASTER_KEY
        - name: METAL_API_AUDITING_INDEX_PREFIX
          value: "{{ .Values.auditing.index_prefix }}"
        - name: METAL_API_AUDITING_INDEX_INTERVAL
          value: "{{ .Values.auditing.index_interval }}"
{{- end }}
{{- if .Values.set_resource_limits }}
        resources:
{{ toYaml .Values.resources.metal_api | indent 10 }}
{{- end }}
        volumeMounts:
{{- if .Values.metal_api.nsq.tls.enabled }}
        - name: {{ .Values.metal_api.nsq.tls.secret_name }}
          mountPath: /certs/nsq/
          readOnly: true
{{- end }}
{{- if .Values.metal_api.grpc.tls.enabled }}
        - name: grpc
          mountPath: /certs/grpc/
          readOnly: true
{{- end }}
{{- if .Values.metal_api.bmc.superuser.enabled }}
        - name: bmc
          mountPath: /bmc
          readOnly: true
{{- end }}
        - name: masterdata-api-tls
          mountPath: /certs/masterdata-api/
          readOnly: true
      volumes:
{{- if .Values.metal_api.nsq.tls.enabled }}
      - name: {{ .Values.metal_api.nsq.tls.secret_name }}
        secret:
          secretName: {{ .Values.metal_api.nsq.tls.secret_name }}
{{- end }}
{{- if .Values.metal_api.grpc.tls.enabled }}
      - name: grpc
        secret:
          secretName: metal-api-grpc
{{- end }}
{{- if .Values.metal_api.bmc.superuser.enabled }}
      - name: bmc
        secret:
          secretName: metal-api-bmc
{{- end }}
      - name: masterdata-api-tls
        secret:
          secretName: masterdata-api-tls
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: metal-api
  name: metal-api
spec:
  ports:
  - name: "{{ .Values.ports.metal_api }}"
    port: {{ .Values.ports.metal_api }}
    targetPort: 8080
  - name: "{{ .Values.ports.metal_api_grpc }}"
    port: {{ .Values.ports.metal_api_grpc }}
    targetPort: 50051
  - name: "{{ .Values.ports.metal_api_metrics }}"
    port: {{ .Values.ports.metal_api_metrics }}
    targetPort: 2112
  selector:
    app: metal-api
---
apiVersion: batch/v1
kind: Job
metadata:
  name: metal-api-initdb
  labels:
    job: metal-api-initdb
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  template:
    metadata:
      name: metal-api-initdb
      labels:
        job: metal-api-initdb
    spec:
      restartPolicy: Never
      enableServiceLinks: False
      containers:
      - name: initdb
        image: {{ .Values.images.metal_api.image }}:{{ .Values.images.metal_api.tag }}
        imagePullPolicy: {{ .Values.images.metal_api.imagePullPolicy }}
        command: ["/metal-api"]
        args: ["initdb"]
        env:
        - name: METAL_API_LOG_LEVEL
          value: {{ .Values.metal_api.log_level }}
        - name: METAL_API_DB_ADDR
          value: {{ .Values.metal_api.db_address }}
        - name: METAL_API_DB_PASSWORD
          value: {{ .Values.metal_api.db_password }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: metal-api-masterdata
  labels:
    app: metal-api
data:
  image.yaml: |
    {{ .Values.metal_api.images | nindent 4 }}
  size.yaml: |
    {{ .Values.metal_api.sizes | nindent 4 }}
  partition.yaml: |
    {{ .Values.metal_api.partitions | nindent 4 }}
  network.yaml: |
    {{ .Values.metal_api.networks | nindent 4 }}
  ip.yaml: |
    {{ .Values.metal_api.ips | nindent 4 }}
  filesystemlayouts.yaml: |
    {{ .Values.metal_api.filesystemlayouts | nindent 4 }}
  sizeimageconstraints.yaml: |
    {{ .Values.metal_api.sizeimageconstraints | nindent 4 }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: metal-api-create-masterdata
  labels:
    job: metal-api-create-masterdata
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  template:
    metadata:
      name: metal-api-create-masterdata
      labels:
        job: metal-api-create-masterdata
    spec:
      restartPolicy: Never
      containers:
      - name: metalctl
        image: {{ .Values.images.metalctl.image }}:{{ .Values.images.metalctl.tag }}
        imagePullPolicy: {{ .Values.images.metalctl.imagePullPolicy }}
        env:
        - name: METALCTL_API_URL
          value: http://metal-api:{{ .Values.ports.metal_api }}{{ .Values.metal_api.base_path }}
        - name: METALCTL_HMAC
          valueFrom:
            secretKeyRef:
              name: metal-api
              key: admin_key
        command:
          - sh
          - -c
          - |
              set -exu
              /metalctl image apply -f /masterdata/image.yaml
              /metalctl partition apply -f /masterdata/partition.yaml
              /metalctl size apply -f /masterdata/size.yaml
              /metalctl network apply -f /masterdata/network.yaml
              /metalctl network ip apply -f /masterdata/ip.yaml
              /metalctl filesystemlayout apply -f /masterdata/filesystemlayouts.yaml
              /metalctl size imageconstraint apply -f /masterdata/sizeimageconstraints.yaml
        volumeMounts:
        - name: masterdata
          mountPath: /masterdata
      initContainers:
      - name: wait-for-api
        image: {{ .Values.images.metalctl.image }}:{{ .Values.images.metalctl.tag }}
        imagePullPolicy: {{ .Values.images.metalctl.imagePullPolicy }}
        env:
        - name: METALCTL_API_URL
          value: http://metal-api:{{ .Values.ports.metal_api }}{{ .Values.metal_api.base_path }}
        - name: METALCTL_HMAC
          valueFrom:
            secretKeyRef:
              name: metal-api
              key: admin_key
        command:
          - sh
          - -c
          - |
              set -exu
              until /metalctl health; do echo "." && sleep 2; done
      volumes:
        - name: masterdata
          configMap:
            name: metal-api-masterdata
            items:
            - key: image.yaml
              path: image.yaml
            - key: size.yaml
              path: size.yaml
            - key: partition.yaml
              path: partition.yaml
            - key: network.yaml
              path: network.yaml
            - key: ip.yaml
              path: ip.yaml
            - key: filesystemlayouts.yaml
              path: filesystemlayouts.yaml
            - key: sizeimageconstraints.yaml
              path: sizeimageconstraints.yaml
---
apiVersion: batch/v1
kind: Job
metadata:
  name: metal-api-migrate-db
  labels:
    job: metal-api-migrate-db
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  template:
    metadata:
      name: metal-api-migrate-db
      labels:
        job: metal-api-migrate-db
    spec:
      restartPolicy: Never
      containers:
      - name: migration
        image: {{ .Values.images.metal_api.image }}:{{ .Values.images.metal_api.tag }}
        imagePullPolicy: {{ .Values.images.metal_api.imagePullPolicy }}
        command:
        - /metal-api
        - migrate
        env:
        - name: METAL_API_LOG_LEVEL
          value: {{ .Values.metal_api.log_level }}
        - name: METAL_API_DB_ADDR
          value: {{ .Values.metal_api.db_address }}
        - name: METAL_API_DB_PASSWORD
          value: {{ .Values.metal_api.db_password }}
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: metal-api-liveliness
  labels:
    job: metal-api-liveliness
spec:
  schedule: "*/1 * * * *"
  failedJobsHistoryLimit: 1
  successfulJobsHistoryLimit: 1
  concurrencyPolicy: Replace
  jobTemplate:
    spec:
      backoffLimit: 3
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - name: trigger-machine-liveliness
            image: {{ .Values.images.metal_api.image }}:{{ .Values.images.metal_api.tag }}
            imagePullPolicy: {{ .Values.images.metal_api.imagePullPolicy }}
            command:
            - /metal-api
            - machine-liveliness
            env:
            - name: METAL_API_LOG_LEVEL
              value: {{ .Values.metal_api.log_level }}
            - name: METAL_API_DB_ADDR
              value: {{ .Values.metal_api.db_address }}
            - name: METAL_API_DB_PASSWORD
              value: {{ .Values.metal_api.db_password }}
{{- if .Values.metal_api.headscale.enabled }}
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: metal-api-machines-vpn-connected
  labels:
    job: metal-api-machines-vpn-connected
spec:
  schedule: "*/1 * * * *"
  failedJobsHistoryLimit: 1
  successfulJobsHistoryLimit: 1
  concurrencyPolicy: Replace
  jobTemplate:
    spec:
      backoffLimit: 3
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - name: metal-api
            image: {{ .Values.images.metal_api.image }}:{{ .Values.images.metal_api.tag }}
            imagePullPolicy: {{ .Values.images.metal_api.imagePullPolicy }}
            command:
            - /metal-api
            - machines-vpn-connected
            env:
            - name: METAL_API_LOG_LEVEL
              value: {{ .Values.metal_api.log_level }}
            - name: METAL_API_DB_ADDR
              value: {{ .Values.metal_api.db_address }}
            - name: METAL_API_DB_PASSWORD
              value: {{ .Values.metal_api.db_password }}
            - name: METAL_API_HEADSCALE_API_KEY
              value: "{{ .Values.metal_api.headscale.api_key }}"
            - name: METAL_API_HEADSCALE_ADDR
              value: {{ .Values.metal_api.headscale.internal_api_address }}
            - name: METAL_API_HEADSCALE_CP_ADDR
              value: {{ .Values.metal_api.headscale.control_plane_address }}
{{- end }}
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: metal-api-resurrection
  labels:
    job: metal-api-resurrection
spec:
  schedule: "0 * * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  concurrencyPolicy: Replace
  jobTemplate:
    spec:
      backoffLimit: 3
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - name: trigger-machine-resurrection
            image: {{ .Values.images.metal_api.image }}:{{ .Values.images.metal_api.tag }}
            imagePullPolicy: {{ .Values.images.metal_api.imagePullPolicy }}
            command:
            - /metal-api
            - resurrect-machines
            env:
            - name: METAL_API_LOG_LEVEL
              value: {{ .Values.metal_api.log_level }}
            - name: METAL_API_DB_ADDR
              value: {{ .Values.metal_api.db_address }}
            - name: METAL_API_DB_PASSWORD
              value: {{ .Values.metal_api.db_password }}
            - name: METAL_API_IPAM_GRPC_SERVER_ENDPOINT
              value: {{ .Values.metal_api.ipam_grpc_server_endpoint }}
            - name: METAL_API_NSQLOOKUPD_ADDR
              value: {{ .Values.metal_api.nsq.lookupd_address }}
            - name: METAL_API_NSQD_TCP_ADDR
              value: {{ .Values.metal_api.nsq.tcp_address }}
            - name: METAL_API_NSQD_HTTP_ENDPOINT
              value: {{ .Values.metal_api.nsq.http_address }}
{{- if .Values.metal_api.nsq.tls.enabled }}
            - name: METAL_API_NSQD_CA_CERT_FILE
              value: /certs/nsq/ca.pem
            - name: METAL_API_NSQD_CLIENT_CERT_FILE
              value: /certs/nsq/client.pem
{{- end }}
            volumeMounts:
{{- if .Values.metal_api.nsq.tls.enabled }}
            - name: {{ .Values.metal_api.nsq.tls.secret_name }}
              mountPath: /certs/nsq/
              readOnly: true
{{- end }}
          volumes:
{{- if .Values.metal_api.nsq.tls.enabled }}
          - name: {{ .Values.metal_api.nsq.tls.secret_name }}
            secret:
              secretName: {{ .Values.metal_api.nsq.tls.secret_name }}
{{- end }}

{{- if .Values.hpa.metal_api.enabled }}
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  creationTimestamp: null
  name: metal-api
spec:
  maxReplicas: {{ .Values.hpa.metal_api.max }}
  minReplicas: {{ .Values.hpa.metal_api.min }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: metal-api
  targetCPUUtilizationPercentage: {{ .Values.hpa.metal_api.cpu_percentage }}
{{- end }}
